#!/usr/bin/env bash
# Transfers a file from our client to a server.


if [[ $# -lt 3 ]]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit
fi

src_path="$1"
host="$2"
user="$3"
id_file="$4"

scp -i "$id_file" -o StrictHostKeyChecking "no" "$src_path" "$user"@"$host":~/
