#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80
# Querying Nginx at its root (/) with a GET request (requesting a page)
# 	   curl http://34.198.248.145/   --> returns string "Holberton School"
#	   curl http://34.198.248.145/   --> returns header info
# Configures an Nginx server so that /redirect_me is redirecting to another page.
# Configures an Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
# configures Nginx so that its HTTP response contains a custom header (on web-01 and web-02) - X-Served-By.


# shellcheck disable=SC2154

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start

# Initialize static pages
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

host=$(hostname)
ERR='\terror_page 404 /404.html;'
ERR_LOC='\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}'
ADD_HDR_XSB='\tadd_header X-Served-By '"${host};"

# See if the redirect location block exists
location=$(sudo grep "	location = /redirect_me {" /etc/nginx/sites-available/default)
# See if error handling is defined
errdef=$(sudo grep "	error_page 404 /404.html" /etc/nginx/sites-available/default)
# Check header
xsb=$(sudo grep "	add_header X-Served-By" /etc/nginx/sites-available/default)

if [ -z "$location" ]
then
	# Delete non-exact location block
	#sudo sed -i '/\n\tlocation /redirect_me {\n\t\treturn 301 https://www.google.com;\n\t}/d' /etc/nginx/sites-available/default

	# Append a location block for 301 redirection
	sudo sed -i '/server_name _/a\\n\tlocation = /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default
else
	#sudo sed -i 's!\n\tlocation = /redirect_me {\n\t\treturn 301 https://www.google.com;\n\t}!\n\tlocation = /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}!' /etc/nginx/sites-available/default
	sudo sed -i 's!https://www.google.com!https://www.youtube.com/watch?v=QH2-TGUlwu4!' /etc/nginx/sites-available/default
fi

if [ -z "$errdef" ]
then
	# Error handling not defined yet
	sudo sed -i '/server_name _/a\\n'"$ERR"'\n\n'"$ERR_LOC" /etc/nginx/sites-available/default
fi

if [ -z "$xsb" ]
then
	# No X-Served-By header yet
	sudo sed -i '/server_name _/a\\n'"$ADD_HDR_XSB" /etc/nginx/sites-available/default
fi

sudo service nginx restart
