#!/usr/bin/env bash
# Installs and configure HAproxy on your lb-01 server.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo apt-get -y install haproxy

fend=$(sudo grep -xi "frontend web" /etc/haproxy/haproxy.cfg)
bend=$(sudo grep -xi "backend web_backend" /etc/haproxy/haproxy.cfg)
init=$(sudo grep -xi "ENABLED=1" /etc/default/haproxy)

FRONTEND='frontend web\n\tbind :80,:8080,:8000\n\tmode http\n\tdefault_backend web_backend'
BACKEND='backend web_backend\n\tbalance roundrobin\n\tmode http\n\tserver 93069-web-01 54.146.64.105:80 check\n\tserver 93069-web-02 54.90.28.253:80 check'
INIT='ENABLED=1'

if [ -z "$fend" ]
then
	# Add frontend configuration
	echo -e "\n$FRONTEND" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
fi

if [ -z "$bend" ]
then
	# Add backend configuration
	echo -e "\n$BACKEND" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
fi

if [ -z "$init" ]
then
	init0=$(sudo grep -xi "ENABLED=0" /etc/default/haproxy)
	if [ -n "$init0" ]
	then
		sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
	else
		# Enable init
		echo -e "\n$INIT" | sudo tee -a /etc/default/haproxy > /dev/null
	fi
fi

sudo service haproxy start
