#!/usr/bin/env bash
###################################################
# This script reads from, and edits the contents of /etc/password.
###################################################

# file="/etc/passwd"
file="school"

while read -r line
do
	echo "$line"
	trimmed=$(echo "$line" | cut -d : -f 1,3,6)
	echo "$trimmed"
done < $file
