#!/usr/bin/env bash
###################################################
# This script parses apache logs.
###################################################


awk -F" " '{print $1 " "  $9}' apache-access.log
