#!/usr/bin/env bash
###################################################
# This script print the text Best School ten times.
###################################################

i=0

while [ $i -lt 10 ]
do
	echo "Best School"

	if [ $i -eq 8 ]
	then
		echo "Hi"
	fi

	(( i++ ))
done
