#!/usr/bin/env bash
###################################################
# This script print the text Best School ten times.
###################################################

i=1

while [ $i -lt 21 ]
do
	case $i in
		4)
			echo "4"
			echo "bad luck from China";;
		9)
			echo 9
			echo "bad luck from Japan";;
		17)
			echo 17
			echo "bad luck from Italy";;
		*)
			echo "$i";;
	esac
	(( i++ ))
done
