#!/usr/bin/env bash
###################################################
# This script print the text Best School ten times.
###################################################

hour=0
minute=1

while [ $hour -lt 13 ]
do
	echo "Hour: $hour"

	while [ $minute -lt 60 ]
	do
		echo $minute
		(( minute++ ))
	done

	(( minute=1 ))  # reset minute counter
	(( hour++ ))
done
