#!/usr/bin/env bash
###################################################
# This script reads from, and edits the contents of /etc/password.
###################################################

file="school"

while read -r line
do
	username=$(echo "$line" | cut -d : -f 1)
	group_id=$(echo "$line" | cut -d : -f 4)
	home_dir=$(echo "$line" | cut -d : -f 6)
	shell=$(echo "$line" | cut -d : -f 7)
	user_id=$(echo "$line" | cut -d : -f 3)
	passwd=$(echo "$line" | cut -d : -f 2)
	user_info=$(echo "$line" | cut -d : -f 5)
	echo "The user $username is part of the $group_id gang, lives in $home_dir and rides $shell. $user_id's place is protected by the passcode $passwd, more info about the user here: $user_info"
done < $file
