#!/usr/bin/env bash
# Configures the hosts file in `/etc/` directory.

line_no=0

while read line
do
	(( line_no++ ))
done < hsts

while [[ "$line_no" > 0 ]]
do
	echo "$line"
	match=$(sed -n '/facebook.com/p')
	echo $match $line_no
	if [ -n "$match" ]
	then
		trim=$(echo "$match" | cut -f 2-)
		echo $trim
		new_line="8.8.8.8	$trim"
		sed -i "/facebook.com/c\\$new_line" hsts
	fi
	(( line_no++ ))
done < hsts

# sed -i '2s/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/8.8.8.8/' hsts
