#!/usr/bin/env bash
# Gracefully reload Gunicorn application server in a way that prevents downtime.

# shellcheck disable=SC2009
ps aux | grep gunicorn | grep web_dynamic.2-hbnb | head -1 | awk '{ print $2 }' | xargs kill -HUP
